### ISSUE TITLE
Error parsing string literals with escaped backslash

### ISSUE THREAD

**Issue by jeswr** [rdfjs/N3.js#238] opened 2021-01-13 00:47 UTC
## Expected behavior
The following code to run with with ~`quadSet1` and~ `quadSet2` being set to arrays quads.
```ts
const n3 = require("n3")
const parser = new n3.Parser();
```
~const quadSet1 = parser.parse('<http://example.org/schema> <http://example.org/pattern> "\\" .')~
```ts
const quadSet2 = parser.parse('<http://example.org/schema> <http://example.org/pattern> "^\\d{3}" .')
```

## Actual behavior
`Error: Unexpected ""\"" on line 1` is thrown `at N3Lexer._syntaxError in  — line 466`

There minimal example is on [runkit](https://runkit.com/jeswr/5ffe408b019e7d001dfb0d5e)

## Use case
Parsing regex patterns in SHACL constraints - for instance the following property shape
```
ex:SSNPropertShape
 sh:path ex:ssn ;
 sh:name "Social Security Number" ;
 sh:datatype xsd:string ;
 sh:maxCount 1 ;
 sh:pattern "^\\d{3}-\\d{2}-\\d{4}$" ;
 sh:order 1 .
 ```

Edit:
I now realise that in most cases one would actually be parsing `<http://example.org/schema> <http://example.org/pattern> "^\\\\d{3}" .`, however as far as I know `quadSet2 ` is still valid syntax.

**Comment by RubenVerborgh** [comment] 2021-01-13 08:45
Duplicate of #178.

> however as far as I know `quadSet2 ` is still valid syntax.

It's not, but the reason is subtle.

Recall that you are writing JavaScript there. When writing any string in JavaScript, Turtle or anything else, you need to apply JavaScript escaping _on top of that_.

When you try
```javascript
console.log("^\\d{3}");
```
it's easy to see that you only passed 1 backslash to the Turtle parser, not 2. Hence the parser is correct to complain.

**Closed by RubenVerborgh** 2021-01-13 08:45 UTC
