### ISSUE TITLE
Node 15 compatibility

### ISSUE THREAD

**Issue by RubenVerborgh** [rdfjs/N3.js#229] opened 2020-10-28 09:27 UTC
Support for Node 15 is currently broken: https://travis-ci.org/github/rdfjs/N3.js/builds/739533351

**Comment by rubensworks** [comment] 2020-10-28 10:21
I first thought this was caused by [the way the main module is required](https://github.com/rdfjs/N3.js/blob/master/spec/parser.js#L1), but I do the same thing [here](https://github.com/rubensworks/microdata-rdf-streaming-parser.js/blob/master/spec/parser.js#L1), which is running fine on Node 15.

So I suspect it has to do with something in the `package.json`.

**Comment by jeswr** [comment] 2024-07-29 22:51
Node 15 long deprecated, closing issue.

**Closed by jeswr** 2024-07-29 22:51 UTC
Labels: bug
