### ISSUE TITLE
Gracefully failing in turtle predicate list clause

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfjs/N3.js#282] opened 2022-04-11 20:07 UTC
I'd expect the following turtle snippet to gracefully throw a syntax error. Instead, it throws with a message: `Cannot read propery 'subject' of undefined`.

```turtle
<a:a> <b:b> <c:c> ; ]
```
```sh
N3.js/lib/N3Parser.js:114
    this._subject = context.subject;
                            ^

TypeError: Cannot read property 'subject' of undefined
    at N3Parser._restoreContext (/home/lrd900/triply/N3.js/lib/N3Parser.js:114:29)
    at N3Parser._readBlankNodeTail (/home/lrd900/triply/N3.js/lib/N3Parser.js:401:10)
    at N3Parser._readPredicate (/home/lrd900/triply/N3.js/lib/N3Parser.js:300:36)
    at /home/lrd900/triply/N3.js/lib/N3Parser.js:1073:127
    at N3Lexer._tokenizeToEnd (/home/lrd900/triply/N3.js/lib/N3Lexer.js:385:7)
    at ReadStream.<anonymous> (/home/lrd900/triply/N3.js/lib/N3Lexer.js:515:22)
    at ReadStream.emit (events.js:400:28)

```

**Comment by wouterbeek** [comment] 2022-04-14 17:49
### Expected behavior

With `<a:a> <b:b> <c:c> ; ]` I expect the following feedback:

1. The line at which this error occurs.  This should be the line where the closing square bracket appears.
2. A message about the parser not being able to read a _predicate_ term.  (Notice that is specifically does not make sense to be looking for a _subject_ term after a semi-colon.)

**Closed** 2022-04-14 19:27 UTC
Labels: bug

**Comment by RubenVerborgh** [comment] 2022-04-14 19:28
> * The line at which this error occurs.  This should be the line where the closing square bracket appears, since that is where the parser figures out that something is wrong, and that is also the line where the user can check the data and figure out that something is wrong.

Check

> * A message about the parser not being able to read a _predicate_ term.  (Notice that is specifically does not make sense to be looking for a _subject_ term after a semi-colon.)

The actual message will be about the unexpected `]`.
Note that the parser was never looking for a subject; instead, it was trying to restore the subject in which the blank node occurred—which doesn't exist because there never was a blank node in the first place.
